name: jn_smarter_iptv_player_pro
description: JN Smarter IPTV Player Pro — Flutter frontend for the local IPTV backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  file_picker: ^12.0.0
  # video_player: ^2.8.6
  video_player: ^2.10.0
  intl: ^0.19.0
  web: ^1.0.0
  fvp: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
